// ─── SEED DATA ────────────────────────────────────────────────────────────────
// Sources: AHA Annual Survey 2022-2024, Becker's Hospital Review 2026,
// Definitive Health HospitalView, Wikipedia, hospital press releases

export const IDN_GROUPS = [
  { rank: 1,  name: "HCA Healthcare",             hq_city: "Nashville",        hq_state: "TN", total_hospitals: 190, total_beds: 41000, net_patient_revenue_b: 56.3, ownership_type: "For-Profit",  states_covered: 21 },
  { rank: 2,  name: "Veterans Health Administration", hq_city: "Washington",   hq_state: "DC", total_hospitals: 170, total_beds: 25200, net_patient_revenue_b: null,  ownership_type: "Government",  states_covered: 50 },
  { rank: 3,  name: "CommonSpirit Health",         hq_city: "Chicago",          hq_state: "IL", total_hospitals: 158, total_beds: 19000, net_patient_revenue_b: 29.4, ownership_type: "Non-Profit",  states_covered: 21 },
  { rank: 4,  name: "LifePoint Health",            hq_city: "Brentwood",        hq_state: "TN", total_hospitals: 135, total_beds: 16000, net_patient_revenue_b: 10.2, ownership_type: "For-Profit",  states_covered: 30 },
  { rank: 5,  name: "Ascension Health",            hq_city: "St. Louis",        hq_state: "MO", total_hospitals: 119, total_beds: 15162, net_patient_revenue_b: 22.0, ownership_type: "Non-Profit",  states_covered: 19 },
  { rank: 6,  name: "ScionHealth",                 hq_city: "Louisville",       hq_state: "KY", total_hospitals: 94,  total_beds: 8200,  net_patient_revenue_b: 4.1,  ownership_type: "For-Profit",  states_covered: 25 },
  { rank: 7,  name: "Trinity Health",              hq_city: "Livonia",          hq_state: "MI", total_hospitals: 92,  total_beds: 14914, net_patient_revenue_b: 19.5, ownership_type: "Non-Profit",  states_covered: 26 },
  { rank: 8,  name: "Advocate Health",             hq_city: "Charlotte",        hq_state: "NC", total_hospitals: 69,  total_beds: 10615, net_patient_revenue_b: 27.0, ownership_type: "Non-Profit",  states_covered: 6  },
  { rank: 9,  name: "Christus Health",             hq_city: "Irving",           hq_state: "TX", total_hospitals: 66,  total_beds: 7500,  net_patient_revenue_b: 7.2,  ownership_type: "Non-Profit",  states_covered: 7  },
  { rank: 10, name: "Community Health Systems",    hq_city: "Franklin",         hq_state: "TN", total_hospitals: 65,  total_beds: 9046,  net_patient_revenue_b: 12.3, ownership_type: "For-Profit",  states_covered: 16 },
  { rank: 11, name: "AdventHealth",                hq_city: "Altamonte Springs",hq_state: "FL", total_hospitals: 57,  total_beds: 8809,  net_patient_revenue_b: 14.0, ownership_type: "Non-Profit",  states_covered: 9  },
  { rank: 12, name: "Sanford Health",              hq_city: "Sioux Falls",      hq_state: "SD", total_hospitals: 56,  total_beds: 5800,  net_patient_revenue_b: 6.8,  ownership_type: "Non-Profit",  states_covered: 9  },
  { rank: 13, name: "Mercy",                       hq_city: "St. Louis",        hq_state: "MO", total_hospitals: 55,  total_beds: 7200,  net_patient_revenue_b: 8.1,  ownership_type: "Non-Profit",  states_covered: 6  },
  { rank: 14, name: "Prime Healthcare",            hq_city: "Ontario",          hq_state: "CA", total_hospitals: 54,  total_beds: 6324,  net_patient_revenue_b: 4.5,  ownership_type: "For-Profit",  states_covered: 14 },
  { rank: 15, name: "Baylor Scott & White Health", hq_city: "Dallas",           hq_state: "TX", total_hospitals: 53,  total_beds: 7100,  net_patient_revenue_b: 11.2, ownership_type: "Non-Profit",  states_covered: 3  },
  { rank: 16, name: "Providence",                  hq_city: "Renton",           hq_state: "WA", total_hospitals: 51,  total_beds: 9256,  net_patient_revenue_b: 24.0, ownership_type: "Non-Profit",  states_covered: 6  },
  { rank: 17, name: "Tenet Healthcare",            hq_city: "Dallas",           hq_state: "TX", total_hospitals: 50,  total_beds: 12073, net_patient_revenue_b: 20.0, ownership_type: "For-Profit",  states_covered: 18 },
  { rank: 18, name: "Bon Secours Mercy Health",    hq_city: "Cincinnati",       hq_state: "OH", total_hospitals: 47,  total_beds: 5500,  net_patient_revenue_b: 11.0, ownership_type: "Non-Profit",  states_covered: 7  },
  { rank: 19, name: "Ochsner Health",              hq_city: "New Orleans",      hq_state: "LA", total_hospitals: 47,  total_beds: 4800,  net_patient_revenue_b: 4.7,  ownership_type: "Non-Profit",  states_covered: 4  },
  { rank: 20, name: "UPMC",                        hq_city: "Pittsburgh",       hq_state: "PA", total_hospitals: 40,  total_beds: 8000,  net_patient_revenue_b: 26.0, ownership_type: "Non-Profit",  states_covered: 5  },
];

export const IDN_HOSPITALS: { idn_rank: number; hospitals: { name: string; city: string; state: string; beds: number | null }[] }[] = [
  { idn_rank: 1, hospitals: [
    { name: "HCA Florida Kendall Hospital", city: "Miami", state: "FL", beds: 725 },
    { name: "Sunrise Hospital and Medical Center", city: "Las Vegas", state: "NV", beds: 716 },
    { name: "Medical City Dallas", city: "Dallas", state: "TX", beds: 694 },
    { name: "Chippenham Hospital", city: "Richmond", state: "VA", beds: 670 },
    { name: "TriStar Centennial Medical Center", city: "Nashville", state: "TN", beds: 741 },
    { name: "St. David's Medical Center", city: "Austin", state: "TX", beds: 354 },
    { name: "Wesley Medical Center Wichita", city: "Wichita", state: "KS", beds: 760 },
    { name: "Methodist Hospital San Antonio", city: "San Antonio", state: "TX", beds: 900 },
  ]},
  { idn_rank: 2, hospitals: [
    { name: "VA Greater Los Angeles Healthcare System", city: "Los Angeles", state: "CA", beds: 389 },
    { name: "VA New York Harbor Healthcare", city: "New York", state: "NY", beds: 450 },
    { name: "VA Medical Center Houston", city: "Houston", state: "TX", beds: 479 },
    { name: "VA Medical Center Boston", city: "Boston", state: "MA", beds: 375 },
    { name: "VA Medical Center Chicago", city: "Chicago", state: "IL", beds: 215 },
    { name: "VA Medical Center Pittsburgh", city: "Pittsburgh", state: "PA", beds: 186 },
  ]},
  { idn_rank: 3, hospitals: [
    { name: "CHI St. Luke's Baylor St. Luke's Medical Center", city: "Houston", state: "TX", beds: 850 },
    { name: "CommonSpirit Mercy Medical Center Des Moines", city: "Des Moines", state: "IA", beds: 802 },
    { name: "St. Anthony Hospital Oklahoma City", city: "Oklahoma City", state: "OK", beds: 555 },
    { name: "Penrose Hospital", city: "Colorado Springs", state: "CO", beds: 364 },
    { name: "St. Joseph Medical Center Houston", city: "Houston", state: "TX", beds: 792 },
  ]},
  { idn_rank: 4, hospitals: [
    { name: "Conemaugh Memorial Medical Center", city: "Johnstown", state: "PA", beds: 539 },
    { name: "Highpoint Regional Health", city: "High Point", state: "NC", beds: 391 },
    { name: "Lake Cumberland Regional Hospital", city: "Somerset", state: "KY", beds: 295 },
    { name: "Frye Regional Medical Center", city: "Hickory", state: "NC", beds: 355 },
  ]},
  { idn_rank: 5, hospitals: [
    { name: "Ascension Saint Thomas Hospital West", city: "Nashville", state: "TN", beds: 708 },
    { name: "Ascension Sacred Heart Hospital Pensacola", city: "Pensacola", state: "FL", beds: 566 },
    { name: "Ascension Seton Medical Center Austin", city: "Austin", state: "TX", beds: 424 },
    { name: "Ascension Via Christi St. Francis Wichita", city: "Wichita", state: "KS", beds: 564 },
    { name: "St. John Hospital and Medical Center Detroit", city: "Detroit", state: "MI", beds: 771 },
  ]},
  { idn_rank: 6, hospitals: [
    { name: "Kindred Hospital Louisville", city: "Louisville", state: "KY", beds: 217 },
    { name: "Cornerstone Hospital of Austin", city: "Austin", state: "TX", beds: 118 },
  ]},
  { idn_rank: 7, hospitals: [
    { name: "Trinity Health Ann Arbor Hospital", city: "Ann Arbor", state: "MI", beds: 537 },
    { name: "Loyola University Medical Center", city: "Maywood", state: "IL", beds: 569 },
    { name: "Saint Alphonsus Regional Medical Center Boise", city: "Boise", state: "ID", beds: 381 },
    { name: "St. Joseph's Health Hospital Syracuse", city: "Syracuse", state: "NY", beds: 431 },
  ]},
  { idn_rank: 8, hospitals: [
    { name: "Atrium Health Carolinas Medical Center", city: "Charlotte", state: "NC", beds: 1064 },
    { name: "Atrium Health Wake Forest Baptist", city: "Winston-Salem", state: "NC", beds: 885 },
    { name: "Advocate Christ Medical Center", city: "Oak Lawn", state: "IL", beds: 695 },
    { name: "Atrium Health Navicent Medical Center", city: "Macon", state: "GA", beds: 637 },
    { name: "Aurora St. Luke's Medical Center", city: "Milwaukee", state: "WI", beds: 932 },
  ]},
  { idn_rank: 9, hospitals: [
    { name: "CHRISTUS Spohn Hospital Corpus Christi", city: "Corpus Christi", state: "TX", beds: 660 },
    { name: "CHRISTUS Mother Frances Hospital Tyler", city: "Tyler", state: "TX", beds: 433 },
    { name: "CHRISTUS Health Shreveport-Bossier", city: "Shreveport", state: "LA", beds: 204 },
  ]},
  { idn_rank: 10, hospitals: [
    { name: "Flowers Hospital", city: "Dothan", state: "AL", beds: 365 },
    { name: "Tennova Healthcare Cleveland", city: "Cleveland", state: "TN", beds: 186 },
    { name: "Brandywine Hospital", city: "Coatesville", state: "PA", beds: 169 },
  ]},
  { idn_rank: 11, hospitals: [
    { name: "AdventHealth Orlando", city: "Orlando", state: "FL", beds: 1364 },
    { name: "AdventHealth Tampa", city: "Tampa", state: "FL", beds: 559 },
    { name: "AdventHealth Shawnee Mission", city: "Merriam", state: "KS", beds: 504 },
    { name: "AdventHealth Redmond", city: "Rome", state: "GA", beds: 530 },
    { name: "AdventHealth Winter Park", city: "Winter Park", state: "FL", beds: 422 },
    { name: "AdventHealth Daytona Beach", city: "Daytona Beach", state: "FL", beds: 362 },
    { name: "AdventHealth Altamonte Springs", city: "Altamonte Springs", state: "FL", beds: 341 },
    { name: "AdventHealth Porter", city: "Denver", state: "CO", beds: 368 },
  ]},
  { idn_rank: 12, hospitals: [
    { name: "Sanford USD Medical Center", city: "Sioux Falls", state: "SD", beds: 545 },
    { name: "Sanford Medical Center Fargo", city: "Fargo", state: "ND", beds: 559 },
    { name: "Sanford Bemidji Medical Center", city: "Bemidji", state: "MN", beds: 99 },
  ]},
  { idn_rank: 13, hospitals: [
    { name: "Mercy Hospital Springfield", city: "Springfield", state: "MO", beds: 866 },
    { name: "Mercy Hospital St. Louis", city: "St. Louis", state: "MO", beds: 815 },
    { name: "Mercy Hospital Oklahoma City", city: "Oklahoma City", state: "OK", beds: 370 },
    { name: "Mercy Hospital Fort Smith", city: "Fort Smith", state: "AR", beds: 339 },
    { name: "Mercy Hospital Joplin", city: "Joplin", state: "MO", beds: 471 },
  ]},
  { idn_rank: 14, hospitals: [
    { name: "Centinela Hospital Medical Center", city: "Inglewood", state: "CA", beds: 369 },
    { name: "St. Mary Medical Center Long Beach", city: "Long Beach", state: "CA", beds: 389 },
    { name: "Garden Grove Hospital Medical Center", city: "Garden Grove", state: "CA", beds: 167 },
  ]},
  { idn_rank: 15, hospitals: [
    { name: "Baylor University Medical Center", city: "Dallas", state: "TX", beds: 838 },
    { name: "Baylor Scott & White Medical Center Temple", city: "Temple", state: "TX", beds: 636 },
    { name: "Texas Health Harris Methodist Fort Worth", city: "Fort Worth", state: "TX", beds: 726 },
  ]},
  { idn_rank: 16, hospitals: [
    { name: "Swedish Medical Center First Hill", city: "Seattle", state: "WA", beds: 631 },
    { name: "Providence Regional Medical Center Everett", city: "Everett", state: "WA", beds: 511 },
    { name: "Providence Portland Medical Center", city: "Portland", state: "OR", beds: 403 },
    { name: "Providence Saint Joseph Medical Center Burbank", city: "Burbank", state: "CA", beds: 454 },
    { name: "Providence Alaska Medical Center", city: "Anchorage", state: "AK", beds: 401 },
  ]},
  { idn_rank: 17, hospitals: [
    { name: "Doctors Hospital at Renaissance", city: "Edinburg", state: "TX", beds: 535 },
    { name: "Detroit Medical Center Harper University Hospital", city: "Detroit", state: "MI", beds: 385 },
    { name: "United Regional Health Care System", city: "Wichita Falls", state: "TX", beds: 298 },
  ]},
  { idn_rank: 18, hospitals: [
    { name: "St. Elizabeth Medical Center Edgewood", city: "Edgewood", state: "KY", beds: 551 },
    { name: "Bon Secours St. Mary's Hospital Richmond", city: "Richmond", state: "VA", beds: 391 },
    { name: "Mercy Health Youngstown", city: "Youngstown", state: "OH", beds: 388 },
  ]},
  { idn_rank: 19, hospitals: [
    { name: "Ochsner Medical Center Main Campus", city: "New Orleans", state: "LA", beds: 1023 },
    { name: "Ochsner Medical Center Baton Rouge", city: "Baton Rouge", state: "LA", beds: 283 },
    { name: "Ochsner St. Anne General Hospital", city: "Raceland", state: "LA", beds: 35 },
  ]},
  { idn_rank: 20, hospitals: [
    { name: "UPMC Presbyterian", city: "Pittsburgh", state: "PA", beds: 757 },
    { name: "UPMC Shadyside", city: "Pittsburgh", state: "PA", beds: 520 },
    { name: "UPMC Hamot", city: "Erie", state: "PA", beds: 439 },
    { name: "UPMC Children's Hospital of Pittsburgh", city: "Pittsburgh", state: "PA", beds: 296 },
  ]},
];

export const HOSPITALS_DATA = [
  // MEGA 1000+ BEDS
  { name: "Yale New Haven Hospital", city: "New Haven", state: "CT", beds: 1541, idn_name: "Yale New Haven Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Jackson Memorial Hospital", city: "Miami", state: "FL", beds: 1504, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Baptist Medical Center San Antonio", city: "San Antonio", state: "TX", beds: 1498, idn_name: "Baptist Health System", idn_rank: null, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Montefiore Medical Center Moses Campus", city: "Bronx", state: "NY", beds: 1444, idn_name: "Montefiore Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "AdventHealth Orlando", city: "Orlando", state: "FL", beds: 1364, idn_name: "AdventHealth", idn_rank: 11, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Mount Sinai Hospital New York", city: "New York", state: "NY", beds: 1134, idn_name: "Mount Sinai Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Memorial Hermann Texas Medical Center", city: "Houston", state: "TX", beds: 1089, idn_name: "Memorial Hermann", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Our Lady of the Lake Regional Medical Center", city: "Baton Rouge", state: "LA", beds: 1088, idn_name: "Franciscan Missionaries of Our Lady", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Indiana University Health University Hospital", city: "Indianapolis", state: "IN", beds: 1200, idn_name: "Indiana University Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Beaumont Hospital Royal Oak", city: "Royal Oak", state: "MI", beds: 1070, idn_name: "Corewell Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Spectrum Health Butterworth Hospital", city: "Grand Rapids", state: "MI", beds: 1060, idn_name: "Corewell Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Atrium Health Carolinas Medical Center", city: "Charlotte", state: "NC", beds: 1064, idn_name: "Advocate Health", idn_rank: 8, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "OhioHealth Riverside Methodist Hospital", city: "Columbus", state: "OH", beds: 1059, idn_name: "OhioHealth", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Baptist Medical Center Jacksonville", city: "Jacksonville", state: "FL", beds: 1004, idn_name: "Baptist Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Ochsner Medical Center Main Campus", city: "New Orleans", state: "LA", beds: 1023, idn_name: "Ochsner Health", idn_rank: 19, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "ECU Health Medical Center", city: "Greenville", state: "NC", beds: 1013, idn_name: "ECU Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Tampa General Hospital", city: "Tampa", state: "FL", beds: 1017, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "The Johns Hopkins Hospital", city: "Baltimore", state: "MD", beds: 1038, idn_name: "Johns Hopkins Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Massachusetts General Hospital", city: "Boston", state: "MA", beds: 997, idn_name: "Mass General Brigham", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "NYU Langone Tisch Hospital", city: "New York", state: "NY", beds: 1024, idn_name: "NYU Langone Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "UNC Hospitals", city: "Chapel Hill", state: "NC", beds: 1000, idn_name: "UNC Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Vanderbilt University Medical Center", city: "Nashville", state: "TN", beds: 1097, idn_name: "Vanderbilt Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Ohio State University Wexner Medical Center", city: "Columbus", state: "OH", beds: 1122, idn_name: "The Ohio State University Wexner Medical Center", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "UF Health Shands Hospital", city: "Gainesville", state: "FL", beds: 1145, idn_name: "UF Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Mayo Clinic Hospital Saint Marys Campus", city: "Rochester", state: "MN", beds: 1154, idn_name: "Mayo Clinic", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "UAB Hospital", city: "Birmingham", state: "AL", beds: 1149, idn_name: "UAB Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Barnes-Jewish Hospital", city: "St. Louis", state: "MO", beds: 1216, idn_name: "BJC HealthCare", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Cleveland Clinic Main Campus", city: "Cleveland", state: "OH", beds: 1299, idn_name: "Cleveland Clinic", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Montefiore Medical Center Moses Campus", city: "Bronx", state: "NY", beds: 1444, idn_name: "Montefiore Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Houston Methodist Hospital", city: "Houston", state: "TX", beds: 976, idn_name: "Houston Methodist", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Michigan Medicine University Hospital", city: "Ann Arbor", state: "MI", beds: 951, idn_name: "Michigan Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Duke University Hospital", city: "Durham", state: "NC", beds: 952, idn_name: "Duke Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "The University of Kansas Hospital", city: "Kansas City", state: "KS", beds: 955, idn_name: "University of Kansas Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Aurora St. Luke's Medical Center", city: "Milwaukee", state: "WI", beds: 932, idn_name: "Advocate Health", idn_rank: 8, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Northwestern Memorial Hospital", city: "Chicago", state: "IL", beds: 930, idn_name: "Northwestern Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Methodist Hospital San Antonio", city: "San Antonio", state: "TX", beds: 900, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Texas Health Presbyterian Hospital Dallas", city: "Dallas", state: "TX", beds: 898, idn_name: "Texas Health Resources", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "University Hospitals Cleveland Medical Center", city: "Cleveland", state: "OH", beds: 887, idn_name: "University Hospitals", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Atrium Health Wake Forest Baptist", city: "Winston-Salem", state: "NC", beds: 885, idn_name: "Advocate Health", idn_rank: 8, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Lehigh Valley Hospital Cedar Crest", city: "Allentown", state: "PA", beds: 873, idn_name: "Lehigh Valley Health Network", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Sarasota Memorial Hospital", city: "Sarasota", state: "FL", beds: 839, idn_name: "Sarasota Memorial Health Care System", idn_rank: null, type: "General Acute Care", ownership: "Government" },
  { name: "Baylor University Medical Center", city: "Dallas", state: "TX", beds: 838, idn_name: "Baylor Scott & White Health", idn_rank: 15, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "UCSF Medical Center at Parnassus", city: "San Francisco", state: "CA", beds: 834, idn_name: "UCSF Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "VCU Medical Center", city: "Richmond", state: "VA", beds: 842, idn_name: "VCU Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Forsyth Medical Center", city: "Winston-Salem", state: "NC", beds: 921, idn_name: "Novant Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Cedars-Sinai Medical Center", city: "Los Angeles", state: "CA", beds: 908, idn_name: "Cedars-Sinai", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Inova Fairfax Hospital", city: "Falls Church", state: "VA", beds: 908, idn_name: "Inova Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Grady Memorial Hospital", city: "Atlanta", state: "GA", beds: 953, idn_name: "Grady Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Texas Children's Hospital", city: "Houston", state: "TX", beds: 905, idn_name: "Texas Children's", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Huntsville Hospital", city: "Huntsville", state: "AL", beds: 904, idn_name: "Huntsville Hospital Health System", idn_rank: null, type: "General Acute Care", ownership: "Government" },
  // 500-899 BEDS
  { name: "Miami Valley Hospital", city: "Dayton", state: "OH", beds: 899, idn_name: "Premier Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "MedStar Washington Hospital Center", city: "Washington", state: "DC", beds: 912, idn_name: "MedStar Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Thomas Jefferson University Hospital", city: "Philadelphia", state: "PA", beds: 868, idn_name: "Jefferson Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Mercy Hospital Springfield", city: "Springfield", state: "MO", beds: 866, idn_name: "Mercy", idn_rank: 13, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "New Hanover Regional Medical Center", city: "Wilmington", state: "NC", beds: 855, idn_name: "Novant Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Strong Memorial Hospital", city: "Rochester", state: "NY", beds: 857, idn_name: "University of Rochester Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Brigham and Women's Hospital", city: "Boston", state: "MA", beds: 826, idn_name: "Mass General Brigham", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Mercy Hospital St. Louis", city: "St. Louis", state: "MO", beds: 815, idn_name: "Mercy", idn_rank: 13, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "NYC Health and Hospitals Bellevue", city: "New York", state: "NY", beds: 828, idn_name: "NYC Health + Hospitals", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "CAMC General Hospital", city: "Charleston", state: "WV", beds: 803, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Santa Clara Valley Medical Center", city: "San Jose", state: "CA", beds: 805, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Government" },
  { name: "Renown Regional Medical Center", city: "Reno", state: "NV", beds: 808, idn_name: "Renown Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UPMC Presbyterian", city: "Pittsburgh", state: "PA", beds: 757, idn_name: "UPMC", idn_rank: 20, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Willis-Knighton Medical Center", city: "Shreveport", state: "LA", beds: 756, idn_name: "Willis-Knighton Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "University of Maryland Medical Center", city: "Baltimore", state: "MD", beds: 757, idn_name: "UMMS", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "North Shore University Hospital", city: "Manhasset", state: "NY", beds: 756, idn_name: "Northwell Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Memorial Regional Hospital", city: "Hollywood", state: "FL", beds: 768, idn_name: "Memorial Healthcare System", idn_rank: null, type: "General Acute Care", ownership: "Government" },
  { name: "Tallahassee Memorial HealthCare", city: "Tallahassee", state: "FL", beds: 772, idn_name: "Tallahassee Memorial HealthCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. John Hospital and Medical Center", city: "Detroit", state: "MI", beds: 771, idn_name: "Ascension Health", idn_rank: 5, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "University of Mississippi Medical Center", city: "Jackson", state: "MS", beds: 767, idn_name: "UMMC Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Erlanger Medical Center", city: "Chattanooga", state: "TN", beds: 752, idn_name: "Erlanger Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "WVU Ruby Memorial Hospital", city: "Morgantown", state: "WV", beds: 710, idn_name: "WVU Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "HCA Florida Kendall Hospital", city: "Miami", state: "FL", beds: 725, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Parkview Regional Medical Center", city: "Fort Wayne", state: "IN", beds: 720, idn_name: "Parkview Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Texas Health Harris Methodist Hospital Fort Worth", city: "Fort Worth", state: "TX", beds: 726, idn_name: "Texas Health Resources", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "TriStar Centennial Medical Center", city: "Nashville", state: "TN", beds: 741, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "MetroHealth Medical Center", city: "Cleveland", state: "OH", beds: 731, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "University Medical Center Las Vegas", city: "Las Vegas", state: "NV", beds: 548, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Sunrise Hospital and Medical Center", city: "Las Vegas", state: "NV", beds: 716, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Upstate University Hospital", city: "Syracuse", state: "NY", beds: 714, idn_name: "Upstate Medical University", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Albany Medical Center", city: "Albany", state: "NY", beds: 734, idn_name: "Albany Med Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Maimonides Medical Center", city: "Brooklyn", state: "NY", beds: 711, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "University of Florida Shands Jacksonville", city: "Jacksonville", state: "FL", beds: 695, idn_name: "UF Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Advocate Christ Medical Center", city: "Oak Lawn", state: "IL", beds: 695, idn_name: "Advocate Health", idn_rank: 8, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "University of Cincinnati Medical Center", city: "Cincinnati", state: "OH", beds: 695, idn_name: "UC Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Medical City Dallas", city: "Dallas", state: "TX", beds: 694, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Abbott Northwestern Hospital", city: "Minneapolis", state: "MN", beds: 697, idn_name: "Allina Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Baptist Memorial Hospital Memphis", city: "Memphis", state: "TN", beds: 638, idn_name: "Baptist Memorial Health Care", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Rush University Medical Center", city: "Chicago", state: "IL", beds: 671, idn_name: "Rush University System for Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Chippenham Hospital", city: "Richmond", state: "VA", beds: 670, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "University Health University Hospital", city: "San Antonio", state: "TX", beds: 670, idn_name: "University Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "CHRISTUS Spohn Hospital Corpus Christi", city: "Corpus Christi", state: "TX", beds: 660, idn_name: "Christus Health", idn_rank: 9, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Penn State Health Milton S. Hershey Medical Center", city: "Hershey", state: "PA", beds: 659, idn_name: "Penn State Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Stanford Health Care Stanford Hospital", city: "Stanford", state: "CA", beds: 613, idn_name: "Stanford Health Care", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "University of Chicago Medical Center", city: "Chicago", state: "IL", beds: 640, idn_name: "UChicago Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Froedtert Hospital", city: "Milwaukee", state: "WI", beds: 640, idn_name: "Froedtert Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Atrium Health Navicent Medical Center", city: "Macon", state: "GA", beds: 637, idn_name: "Advocate Health", idn_rank: 8, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Baylor Scott & White Medical Center Temple", city: "Temple", state: "TX", beds: 636, idn_name: "Baylor Scott & White Health", idn_rank: 15, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Ben Taub Hospital", city: "Houston", state: "TX", beds: 636, idn_name: "Harris Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Swedish Medical Center First Hill", city: "Seattle", state: "WA", beds: 631, idn_name: "Providence", idn_rank: 16, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Allegheny General Hospital", city: "Pittsburgh", state: "PA", beds: 631, idn_name: "Allegheny Health Network", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "University of New Mexico Hospital", city: "Albuquerque", state: "NM", beds: 631, idn_name: "UNM Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Stanford Health Care Stanford Hospital", city: "Stanford", state: "CA", beds: 613, idn_name: "Stanford Health Care", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "WellStar Kennestone Regional Medical Center", city: "Marietta", state: "GA", beds: 633, idn_name: "WellStar Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Novant Health Presbyterian Medical Center", city: "Charlotte", state: "NC", beds: 633, idn_name: "Novant Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UC Davis Medical Center", city: "Sacramento", state: "CA", beds: 627, idn_name: "UC Davis Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Kings County Hospital Center", city: "Brooklyn", state: "NY", beds: 627, idn_name: "NYC Health + Hospitals", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "University of Wisconsin Hospital", city: "Madison", state: "WI", beds: 618, idn_name: "UW Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Hartford Hospital", city: "Hartford", state: "CT", beds: 867, idn_name: "Hartford HealthCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Francis Hospital Hartford", city: "Hartford", state: "CT", beds: 617, idn_name: "Trinity Health", idn_rank: 7, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Methodist Healthcare Memphis Hospitals", city: "Memphis", state: "TN", beds: 620, idn_name: "Methodist Le Bonheur Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Maine Medical Center", city: "Portland", state: "ME", beds: 637, idn_name: "MaineHealth", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "OSF Saint Francis Medical Center", city: "Peoria", state: "IL", beds: 617, idn_name: "OSF HealthCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Memorial Hospital Savannah", city: "Savannah", state: "GA", beds: 612, idn_name: "Memorial Health University Medical Center", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "OHSU Hospital", city: "Portland", state: "OR", beds: 576, idn_name: "OHSU", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Long Island Jewish Medical Center", city: "New Hyde Park", state: "NY", beds: 583, idn_name: "Northwell Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Augusta University Medical Center", city: "Augusta", state: "GA", beds: 583, idn_name: "Augusta University Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Greenville Memorial Hospital", city: "Greenville", state: "SC", beds: 728, idn_name: "Prisma Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Medical University of South Carolina", city: "Charleston", state: "SC", beds: 765, idn_name: "MUSC Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Spartanburg Medical Center", city: "Spartanburg", state: "SC", beds: 635, idn_name: "Spartanburg Regional Healthcare System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Sharp Memorial Hospital", city: "San Diego", state: "CA", beds: 677, idn_name: "Sharp HealthCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Baptist Health Louisville", city: "Louisville", state: "KY", beds: 525, idn_name: "Baptist Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UK HealthCare Albert B. Chandler Hospital", city: "Lexington", state: "KY", beds: 945, idn_name: "UK HealthCare", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Stony Brook University Hospital", city: "Stony Brook", state: "NY", beds: 603, idn_name: "Stony Brook Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Emory University Hospital", city: "Atlanta", state: "GA", beds: 579, idn_name: "Emory Healthcare", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Boston Medical Center", city: "Boston", state: "MA", beds: 589, idn_name: "Boston Medical Center Health System", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Loma Linda University Medical Center", city: "Loma Linda", state: "CA", beds: 550, idn_name: "Loma Linda University Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "University of Utah Hospital", city: "Salt Lake City", state: "UT", beds: 561, idn_name: "University of Utah Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "UVM Medical Center", city: "Burlington", state: "VT", beds: 562, idn_name: "University of Vermont Health Network", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Carilion Roanoke Memorial Hospital", city: "Roanoke", state: "VA", beds: 703, idn_name: "Carilion Clinic", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Children's Hospital of Philadelphia", city: "Philadelphia", state: "PA", beds: 594, idn_name: "CHOP", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "University of Iowa Hospitals and Clinics", city: "Iowa City", state: "IA", beds: 879, idn_name: "UI Health Care", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Rex Healthcare", city: "Raleigh", state: "NC", beds: 665, idn_name: "UNC Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "WakeMed Raleigh Campus", city: "Raleigh", state: "NC", beds: 776, idn_name: "WakeMed Health and Hospitals", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Moses H. Cone Memorial Hospital", city: "Greensboro", state: "NC", beds: 547, idn_name: "Cone Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Integris Baptist Medical Center", city: "Oklahoma City", state: "OK", beds: 581, idn_name: "Integris Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Saint Francis Hospital Tulsa", city: "Tulsa", state: "OK", beds: 963, idn_name: "Saint Francis Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Hillcrest Medical Center Tulsa", city: "Tulsa", state: "OK", beds: 656, idn_name: "Ardent Health Services", idn_rank: null, type: "General Acute Care", ownership: "For-Profit" },
  { name: "OU Health University of Oklahoma Medical Center", city: "Oklahoma City", state: "OK", beds: 752, idn_name: "OU Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Nebraska Medicine Nebraska Medical Center", city: "Omaha", state: "NE", beds: 735, idn_name: "Nebraska Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "UAMS Medical Center", city: "Little Rock", state: "AR", beds: 453, idn_name: "UAMS Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Baptist Health Medical Center Little Rock", city: "Little Rock", state: "AR", beds: 697, idn_name: "Baptist Health Arkansas", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Luke's Hospital Kansas City", city: "Kansas City", state: "MO", beds: 647, idn_name: "Saint Luke's Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Cox Medical Center", city: "Springfield", state: "MO", beds: 730, idn_name: "CoxHealth", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Via Christi St. Francis Hospital Wichita", city: "Wichita", state: "KS", beds: 564, idn_name: "Ascension Health", idn_rank: 5, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Wesley Medical Center Wichita", city: "Wichita", state: "KS", beds: 760, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "University of Minnesota Medical Center", city: "Minneapolis", state: "MN", beds: 744, idn_name: "M Health Fairview", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Regions Hospital", city: "St. Paul", state: "MN", beds: 481, idn_name: "HealthPartners", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Hennepin Healthcare", city: "Minneapolis", state: "MN", beds: 479, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Rhode Island Hospital", city: "Providence", state: "RI", beds: 719, idn_name: "Lifespan", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Broward Health Medical Center", city: "Fort Lauderdale", state: "FL", beds: 716, idn_name: "Broward Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Henry Ford Hospital", city: "Detroit", state: "MI", beds: 877, idn_name: "Henry Ford Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Sparrow Hospital", city: "Lansing", state: "MI", beds: 685, idn_name: "Sparrow Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Forrest General Hospital", city: "Hattiesburg", state: "MS", beds: 537, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Dominic Hospital", city: "Jackson", state: "MS", beds: 571, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Baptist Medical Center Jackson", city: "Jackson", state: "MS", beds: 591, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Geisinger Medical Center", city: "Danville", state: "PA", beds: 574, idn_name: "Geisinger", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Temple University Hospital", city: "Philadelphia", state: "PA", beds: 722, idn_name: "Temple Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Hospital of the University of Pennsylvania", city: "Philadelphia", state: "PA", beds: 821, idn_name: "Penn Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "UPMC Shadyside", city: "Pittsburgh", state: "PA", beds: 520, idn_name: "UPMC", idn_rank: 20, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UPMC Hamot", city: "Erie", state: "PA", beds: 439, idn_name: "UPMC", idn_rank: 20, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Intermountain Medical Center", city: "Murray", state: "UT", beds: 507, idn_name: "Intermountain Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "LDS Hospital", city: "Salt Lake City", state: "UT", beds: 520, idn_name: "Intermountain Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Banner University Medical Center Phoenix", city: "Phoenix", state: "AZ", beds: 722, idn_name: "Banner Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Valleywise Health Medical Center", city: "Phoenix", state: "AZ", beds: 563, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "University of Colorado Hospital", city: "Aurora", state: "CO", beds: 669, idn_name: "UCHealth", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Parkland Memorial Hospital", city: "Dallas", state: "TX", beds: 862, idn_name: "Parkland Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Sentara Norfolk General Hospital", city: "Norfolk", state: "VA", beds: 525, idn_name: "Sentara Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Kaiser Permanente Los Angeles Medical Center", city: "Los Angeles", state: "CA", beds: 528, idn_name: "Kaiser Permanente", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "John Muir Medical Center Walnut Creek", city: "Walnut Creek", state: "CA", beds: 556, idn_name: "John Muir Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Sutter Medical Center Sacramento", city: "Sacramento", state: "CA", beds: 524, idn_name: "Sutter Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UCLA Medical Center", city: "Los Angeles", state: "CA", beds: 520, idn_name: "UCLA Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "The Queen's Medical Center", city: "Honolulu", state: "HI", beds: 505, idn_name: "The Queen's Health Systems", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Rochester General Hospital", city: "Rochester", state: "NY", beds: 520, idn_name: "Rochester Regional Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "CHRISTUS Spohn Hospital Alice", city: "Alice", state: "TX", beds: 115, idn_name: "Christus Health", idn_rank: 9, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Summa Health System Akron City Hospital", city: "Akron", state: "OH", beds: 553, idn_name: "Summa Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Providence Alaska Medical Center", city: "Anchorage", state: "AK", beds: 401, idn_name: "Providence", idn_rank: 16, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "JPS Health Network", city: "Fort Worth", state: "TX", beds: 537, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Doctors Hospital at Renaissance", city: "Edinburg", state: "TX", beds: 535, idn_name: "Tenet Healthcare", idn_rank: 17, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Trinity Health Ann Arbor Hospital", city: "Ann Arbor", state: "MI", beds: 537, idn_name: "Trinity Health", idn_rank: 7, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Sanford USD Medical Center", city: "Sioux Falls", state: "SD", beds: 545, idn_name: "Sanford Health", idn_rank: 12, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Sanford Medical Center Fargo", city: "Fargo", state: "ND", beds: 559, idn_name: "Sanford Health", idn_rank: 12, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Tampa", city: "Tampa", state: "FL", beds: 559, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Redmond", city: "Rome", state: "GA", beds: 530, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Shawnee Mission", city: "Merriam", state: "KS", beds: 504, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Elizabeth Medical Center Edgewood", city: "Edgewood", state: "KY", beds: 551, idn_name: "Bon Secours Mercy Health", idn_rank: 18, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Ascension Sacred Heart Hospital Pensacola", city: "Pensacola", state: "FL", beds: 566, idn_name: "Ascension Health", idn_rank: 5, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Legacy Emanuel Medical Center", city: "Portland", state: "OR", beds: 554, idn_name: "Legacy Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Loyola University Medical Center", city: "Maywood", state: "IL", beds: 569, idn_name: "Trinity Health", idn_rank: 7, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Providence Portland Medical Center", city: "Portland", state: "OR", beds: 503, idn_name: "Providence", idn_rank: 16, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Providence Regional Medical Center Everett", city: "Everett", state: "WA", beds: 511, idn_name: "Providence", idn_rank: 16, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UPMC Shadyside", city: "Pittsburgh", state: "PA", beds: 520, idn_name: "UPMC", idn_rank: 20, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Luke's Regional Medical Center Boise", city: "Boise", state: "ID", beds: 420, idn_name: "St. Luke's Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "LSU Health Shreveport", city: "Shreveport", state: "LA", beds: 432, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "University Medical Center New Orleans", city: "New Orleans", state: "LA", beds: 446, idn_name: "LCMC Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  // 200-499 BEDS
  { name: "AdventHealth Winter Park", city: "Winter Park", state: "FL", beds: 422, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Altamonte Springs", city: "Altamonte Springs", state: "FL", beds: 341, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Porter", city: "Denver", state: "CO", beds: 368, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Daytona Beach", city: "Daytona Beach", state: "FL", beds: 362, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth East Orlando", city: "Orlando", state: "FL", beds: 295, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Kissimmee", city: "Kissimmee", state: "FL", beds: 282, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Waterman", city: "Tavares", state: "FL", beds: 288, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Celebration", city: "Celebration", state: "FL", beds: 227, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Heart of Florida", city: "Davenport", state: "FL", beds: 202, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Sebring", city: "Sebring", state: "FL", beds: 204, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Littleton", city: "Littleton", state: "CO", beds: 231, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Ocala", city: "Ocala", state: "FL", beds: 380, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Winnie Palmer for Women and Babies", city: "Orlando", state: "FL", beds: 285, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UChicago Medicine AdventHealth Hinsdale", city: "Hinsdale", state: "IL", beds: 261, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Ochsner Medical Center Baton Rouge", city: "Baton Rouge", state: "LA", beds: 283, idn_name: "Ochsner Health", idn_rank: 19, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Texas Health Huguley Hospital Fort Worth South", city: "Burleson", state: "TX", beds: 197, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "CHRISTUS Mother Frances Hospital Tyler", city: "Tyler", state: "TX", beds: 433, idn_name: "Christus Health", idn_rank: 9, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Norton Hospital Louisville", city: "Louisville", state: "KY", beds: 479, idn_name: "Norton Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Penrose Hospital Colorado Springs", city: "Colorado Springs", state: "CO", beds: 364, idn_name: "CommonSpirit Health", idn_rank: 3, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Harborview Medical Center", city: "Seattle", state: "WA", beds: 413, idn_name: "UW Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "University of Washington Medical Center", city: "Seattle", state: "WA", beds: 432, idn_name: "UW Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Emory Saint Joseph's Hospital", city: "Atlanta", state: "GA", beds: 410, idn_name: "Emory Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Piedmont Atlanta Hospital", city: "Atlanta", state: "GA", beds: 537, idn_name: "Piedmont Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Parkview Regional Medical Center", city: "Fort Wayne", state: "IN", beds: 435, idn_name: "Parkview Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Joseph Regional Medical Center", city: "Mishawaka", state: "IN", beds: 254, idn_name: "Trinity Health", idn_rank: 7, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Memorial Hospital South Bend", city: "South Bend", state: "IN", beds: 474, idn_name: "Beacon Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Cook Children's Medical Center", city: "Fort Worth", state: "TX", beds: 479, idn_name: "Cook Children's Health Care System", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Memorial Hermann Memorial City Medical Center", city: "Houston", state: "TX", beds: 465, idn_name: "Memorial Hermann", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UT Southwestern Medical Center William P. Clements Jr.", city: "Dallas", state: "TX", beds: 460, idn_name: "UT Southwestern", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Roper St. Francis Hospital", city: "Charleston", state: "SC", beds: 386, idn_name: "Roper St. Francis Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AnMed Health Medical Center", city: "Anderson", state: "SC", beds: 427, idn_name: "AnMed Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Trident Medical Center", city: "Charleston", state: "SC", beds: 491, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Bon Secours St. Mary's Hospital Richmond", city: "Richmond", state: "VA", beds: 391, idn_name: "Bon Secours Mercy Health", idn_rank: 18, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Sentara Norfolk General Hospital", city: "Norfolk", state: "VA", beds: 525, idn_name: "Sentara Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Virginia Hospital Center", city: "Arlington", state: "VA", beds: 394, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "George Washington University Hospital", city: "Washington", state: "DC", beds: 385, idn_name: "Universal Health Services", idn_rank: null, type: "Academic Medical Center", ownership: "For-Profit" },
  { name: "Howard University Hospital", city: "Washington", state: "DC", beds: 408, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Zuckerberg San Francisco General Hospital", city: "San Francisco", state: "CA", beds: 391, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Providence Saint Joseph Medical Center Burbank", city: "Burbank", state: "CA", beds: 454, idn_name: "Providence", idn_rank: 16, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Scripps Mercy Hospital San Diego", city: "San Diego", state: "CA", beds: 475, idn_name: "Scripps Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Hoag Hospital Newport Beach", city: "Newport Beach", state: "CA", beds: 498, idn_name: "Hoag Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Torrance Memorial Medical Center", city: "Torrance", state: "CA", beds: 401, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Banner University Medical Center Tucson", city: "Tucson", state: "AZ", beds: 497, idn_name: "Banner Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "HonorHealth Scottsdale Osborn Medical Center", city: "Scottsdale", state: "AZ", beds: 347, idn_name: "HonorHealth", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Mayo Clinic Hospital Phoenix", city: "Phoenix", state: "AZ", beds: 268, idn_name: "Mayo Clinic", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "St. Mary's Regional Medical Center Reno", city: "Reno", state: "NV", beds: 380, idn_name: "Dignity Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Presbyterian Hospital Albuquerque", city: "Albuquerque", state: "NM", beds: 476, idn_name: "Presbyterian Healthcare Services", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Primary Children's Hospital", city: "Salt Lake City", state: "UT", beds: 289, idn_name: "Intermountain Health", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Saint Alphonsus Regional Medical Center Boise", city: "Boise", state: "ID", beds: 381, idn_name: "Trinity Health", idn_rank: 7, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Luke's Regional Medical Center Boise", city: "Boise", state: "ID", beds: 420, idn_name: "St. Luke's Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Billings Clinic", city: "Billings", state: "MT", beds: 286, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Benefis Health System", city: "Great Falls", state: "MT", beds: 500, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Altru Health System", city: "Grand Forks", state: "ND", beds: 280, idn_name: null, idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Rapid City Regional Hospital", city: "Rapid City", state: "SD", beds: 399, idn_name: "Monument Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Children's Mercy Hospital Kansas City", city: "Kansas City", state: "MO", beds: 365, idn_name: "Children's Mercy", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Mercy Hospital Oklahoma City", city: "Oklahoma City", state: "OK", beds: 370, idn_name: "Mercy", idn_rank: 13, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Eskenazi Health", city: "Indianapolis", state: "IN", beds: 315, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Marquette General Hospital", city: "Marquette", state: "MI", beds: 268, idn_name: "UP Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Bronson Methodist Hospital", city: "Kalamazoo", state: "MI", beds: 430, idn_name: "Bronson Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Detroit Medical Center Harper University Hospital", city: "Detroit", state: "MI", beds: 385, idn_name: "Tenet Healthcare", idn_rank: 17, type: "Academic Medical Center", ownership: "For-Profit" },
  { name: "Park Nicollet Methodist Hospital", city: "St. Louis Park", state: "MN", beds: 426, idn_name: "HealthPartners", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UnityPoint Health Iowa Methodist Medical Center", city: "Des Moines", state: "IA", beds: 502, idn_name: "UnityPoint Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Bryan Medical Center East", city: "Lincoln", state: "NE", beds: 308, idn_name: "Bryan Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Essentia Health St. Mary's Medical Center", city: "Duluth", state: "MN", beds: 302, idn_name: "Essentia Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Cloud Hospital", city: "St. Cloud", state: "MN", beds: 489, idn_name: "CentraCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Arkansas Children's Hospital", city: "Little Rock", state: "AR", beds: 336, idn_name: null, idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Mercy Hospital Fort Smith", city: "Fort Smith", state: "AR", beds: 339, idn_name: "Mercy", idn_rank: 13, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Boone Hospital Center", city: "Columbia", state: "MO", beds: 390, idn_name: "BJC HealthCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Missouri Baptist Medical Center", city: "Town and Country", state: "MO", beds: 489, idn_name: "BJC HealthCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Alphonsus Regional Medical Center", city: "Boise", state: "ID", beds: 381, idn_name: "Trinity Health", idn_rank: 7, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "PeaceHealth Sacred Heart Medical Center", city: "Springfield", state: "OR", beds: 361, idn_name: "PeaceHealth", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Marshfield Medical Center", city: "Marshfield", state: "WI", beds: 395, idn_name: "Marshfield Clinic Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Tufts Medical Center", city: "Boston", state: "MA", beds: 415, idn_name: "Tufts Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Beth Israel Deaconess Medical Center", city: "Boston", state: "MA", beds: 649, idn_name: "Beth Israel Lahey Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Eastern Maine Medical Center", city: "Bangor", state: "ME", beds: 411, idn_name: "Northern Light Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Dartmouth Hitchcock Medical Center", city: "Lebanon", state: "NH", beds: 396, idn_name: "Dartmouth Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Hospital of Central Connecticut", city: "New Britain", state: "CT", beds: 414, idn_name: "Hartford HealthCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "The Miriam Hospital", city: "Providence", state: "RI", beds: 247, idn_name: "Lifespan", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Touro Infirmary", city: "New Orleans", state: "LA", beds: 231, idn_name: "LCMC Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Le Bonheur Children's Hospital", city: "Memphis", state: "TN", beds: 255, idn_name: "Methodist Le Bonheur Healthcare", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Wheaton Franciscan All Saints Hospital", city: "Racine", state: "WI", beds: 432, idn_name: "Ascension Health", idn_rank: 5, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Overlake Medical Center", city: "Bellevue", state: "WA", beds: 349, idn_name: "Overlake Medical Center", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Virginia Mason Medical Center", city: "Seattle", state: "WA", beds: 336, idn_name: "Virginia Mason Franciscan Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "SSM Health St. Louis University Hospital", city: "St. Louis", state: "MO", beds: 356, idn_name: "SSM Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Children's Hospital Colorado", city: "Aurora", state: "CO", beds: 444, idn_name: "Children's Hospital Colorado", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "St. Joseph Mercy Ann Arbor Hospital", city: "Ypsilanti", state: "MI", beds: 440, idn_name: "Trinity Health", idn_rank: 7, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Phoebe Putney Memorial Hospital", city: "Albany", state: "GA", beds: 443, idn_name: "Phoebe Putney Health System", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Northeast Georgia Medical Center Gainesville", city: "Gainesville", state: "GA", beds: 557, idn_name: "NGMC", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Sinai Hospital Baltimore", city: "Baltimore", state: "MD", beds: 489, idn_name: "LifeBridge Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Conemaugh Memorial Medical Center", city: "Johnstown", state: "PA", beds: 539, idn_name: "LifePoint Health", idn_rank: 4, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Geisinger Medical Center Danville", city: "Danville", state: "PA", beds: 574, idn_name: "Geisinger", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Allegheny General Hospital Pittsburgh", city: "Pittsburgh", state: "PA", beds: 631, idn_name: "Allegheny Health Network", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "WVU Ruby Memorial Hospital", city: "Morgantown", state: "WV", beds: 710, idn_name: "WVU Medicine", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Mercy Health Youngstown", city: "Youngstown", state: "OH", beds: 388, idn_name: "Bon Secours Mercy Health", idn_rank: 18, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Cincinnati Children's Hospital Medical Center", city: "Cincinnati", state: "OH", beds: 724, idn_name: "Cincinnati Children's", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Christ Hospital Cincinnati", city: "Cincinnati", state: "OH", beds: 555, idn_name: "The Christ Hospital Health Network", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Cleveland Clinic Hillcrest Hospital", city: "Mayfield Heights", state: "OH", beds: 487, idn_name: "Cleveland Clinic", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Parkridge Medical Center", city: "Chattanooga", state: "TN", beds: 416, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Regional One Health Medical Center", city: "Memphis", state: "TN", beds: 371, idn_name: null, idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "University of Louisville Hospital", city: "Louisville", state: "KY", beds: 404, idn_name: "UofL Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "St. Joseph Hospital Lexington", city: "Lexington", state: "KY", beds: 433, idn_name: "CommonSpirit Health", idn_rank: 3, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "St. Anthony Hospital Oklahoma City", city: "Oklahoma City", state: "OK", beds: 555, idn_name: "CommonSpirit Health", idn_rank: 3, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "OSF Saint Francis Medical Center Peoria", city: "Peoria", state: "IL", beds: 617, idn_name: "OSF HealthCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Northwestern Medicine Central DuPage Hospital", city: "Winfield", state: "IL", beds: 404, idn_name: "Northwestern Medicine", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UnityPoint Health Methodist Medical Center Peoria", city: "Peoria", state: "IL", beds: 372, idn_name: "UnityPoint Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Memorial Medical Center Springfield IL", city: "Springfield", state: "IL", beds: 500, idn_name: "Memorial Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Spectrum Health Helen DeVos Children's Hospital", city: "Grand Rapids", state: "MI", beds: 235, idn_name: "Corewell Health", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "ThedaCare Regional Medical Center Appleton", city: "Appleton", state: "WI", beds: 222, idn_name: "ThedaCare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Jacobi Medical Center", city: "Bronx", state: "NY", beds: 457, idn_name: "NYC Health + Hospitals", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Elmhurst Hospital Center", city: "Elmhurst", state: "NY", beds: 545, idn_name: "NYC Health + Hospitals", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "Winthrop University Hospital", city: "Mineola", state: "NY", beds: 591, idn_name: "NYU Langone Health", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "UPMC Altoona", city: "Altoona", state: "PA", beds: 372, idn_name: "UPMC", idn_rank: 20, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Straub Medical Center Honolulu", city: "Honolulu", state: "HI", beds: 159, idn_name: "Hawaii Pacific Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Kapiolani Medical Center for Women and Children", city: "Honolulu", state: "HI", beds: 224, idn_name: "Hawaii Pacific Health", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Doctors Hospital Augusta", city: "Augusta", state: "GA", beds: 357, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Piedmont Columbus Regional", city: "Columbus", state: "GA", beds: 580, idn_name: "Piedmont Healthcare", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "University of Michigan Health West", city: "Wyoming", state: "MI", beds: 250, idn_name: "Michigan Medicine", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Flowers Hospital Dothan", city: "Dothan", state: "AL", beds: 365, idn_name: "Community Health Systems", idn_rank: 10, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Truman Medical Center Lakewood", city: "Kansas City", state: "MO", beds: 443, idn_name: "University Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  // 100-199 BEDS
  { name: "AdventHealth Kissimmee", city: "Kissimmee", state: "FL", beds: 282, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Wesley Chapel", city: "Wesley Chapel", state: "FL", beds: 169, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth North Pinellas", city: "Tarpon Springs", state: "FL", beds: 136, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth DeLand", city: "DeLand", state: "FL", beds: 167, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Zephyrhills", city: "Zephyrhills", state: "FL", beds: 149, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth New Smyrna Beach", city: "New Smyrna Beach", state: "FL", beds: 152, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Palm Coast", city: "Palm Coast", state: "FL", beds: 100, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Arnold Palmer for Children", city: "Orlando", state: "FL", beds: 172, idn_name: "AdventHealth", idn_rank: 11, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "AdventHealth Central Texas", city: "Killeen", state: "TX", beds: 148, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Avista", city: "Louisville", state: "CO", beds: 114, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Parker", city: "Parker", state: "CO", beds: 145, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UChicago Medicine AdventHealth La Grange", city: "La Grange", state: "IL", beds: 159, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UChicago Medicine AdventHealth GlenOaks", city: "Glendale Heights", state: "IL", beds: 122, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UChicago Medicine AdventHealth Bolingbrook", city: "Bolingbrook", state: "IL", beds: 110, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth South Overland Park", city: "Overland Park", state: "KS", beds: 100, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Hendersonville", city: "Hendersonville", state: "NC", beds: 98, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Children's Minnesota Minneapolis", city: "Minneapolis", state: "MN", beds: 369, idn_name: "Children's Minnesota", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Children's National Hospital Washington DC", city: "Washington", state: "DC", beds: 323, idn_name: "Children's National", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Nicklaus Children's Hospital", city: "Miami", state: "FL", beds: 309, idn_name: "Nicklaus Children's Health System", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Lucile Packard Children's Hospital Stanford", city: "Palo Alto", state: "CA", beds: 361, idn_name: "Stanford Health Care", idn_rank: null, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "UC Irvine Medical Center", city: "Orange", state: "CA", beds: 397, idn_name: "UCI Health", idn_rank: null, type: "Academic Medical Center", ownership: "Government" },
  { name: "USC Keck Hospital", city: "Los Angeles", state: "CA", beds: 401, idn_name: "Keck Medicine of USC", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  { name: "Mayo Clinic Hospital Jacksonville", city: "Jacksonville", state: "FL", beds: 304, idn_name: "Mayo Clinic", idn_rank: null, type: "Academic Medical Center", ownership: "Non-Profit" },
  // SMALL-MEDIUM (under 100 beds)
  { name: "AdventHealth Fish Memorial", city: "Orange City", state: "FL", beds: 99, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Castle Rock", city: "Castle Rock", state: "CO", beds: 89, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Gordon", city: "Calhoun", state: "GA", beds: 69, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Winter Garden", city: "Winter Garden", state: "FL", beds: 129, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Manchester", city: "Manchester", state: "KY", beds: 49, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Ottawa", city: "Ottawa", state: "KS", beds: 44, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Murray", city: "Chatsworth", state: "GA", beds: 29, idn_name: "AdventHealth", idn_rank: 11, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "AdventHealth Polk", city: "Columbus", state: "NC", beds: 25, idn_name: "AdventHealth", idn_rank: 11, type: "Critical Access", ownership: "Non-Profit" },
  { name: "AdventHealth Lake Placid", city: "Lake Placid", state: "FL", beds: 33, idn_name: "AdventHealth", idn_rank: 11, type: "Critical Access", ownership: "Non-Profit" },
  { name: "Ochsner St. Anne General Hospital", city: "Raceland", state: "LA", beds: 35, idn_name: "Ochsner Health", idn_rank: 19, type: "Critical Access", ownership: "Non-Profit" },
  { name: "Sanford Bemidji Medical Center", city: "Bemidji", state: "MN", beds: 99, idn_name: "Sanford Health", idn_rank: 12, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Providence St. Patrick Hospital Missoula", city: "Missoula", state: "MT", beds: 214, idn_name: "Providence", idn_rank: 16, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Cleveland Clinic Florida Weston", city: "Weston", state: "FL", beds: 155, idn_name: "Cleveland Clinic", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UCHealth Medical Center of the Rockies", city: "Loveland", state: "CO", beds: 175, idn_name: "UCHealth", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Newton-Wellesley Hospital", city: "Newton", state: "MA", beds: 271, idn_name: "Mass General Brigham", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Wheeling Hospital WV", city: "Wheeling", state: "WV", beds: 272, idn_name: "WVU Medicine", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "UPMC Children's Hospital of Pittsburgh", city: "Pittsburgh", state: "PA", beds: 296, idn_name: "UPMC", idn_rank: 20, type: "Children's Hospital", ownership: "Non-Profit" },
  { name: "Duke Raleigh Hospital", city: "Raleigh", state: "NC", beds: 186, idn_name: "Duke Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Carolinas HealthCare Blue Ridge Morganton", city: "Morganton", state: "NC", beds: 117, idn_name: "Advocate Health", idn_rank: 8, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Kaiser Permanente San Francisco Medical Center", city: "San Francisco", state: "CA", beds: 239, idn_name: "Kaiser Permanente", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "El Camino Health Mountain View", city: "Mountain View", state: "CA", beds: 443, idn_name: "El Camino Health", idn_rank: null, type: "General Acute Care", ownership: "Non-Profit" },
  { name: "Boise VA Medical Center", city: "Boise", state: "ID", beds: 67, idn_name: "Veterans Health Administration", idn_rank: 2, type: "General Acute Care", ownership: "Government" },
  { name: "Alaska Regional Hospital Anchorage", city: "Anchorage", state: "AK", beds: 250, idn_name: "HCA Healthcare", idn_rank: 1, type: "General Acute Care", ownership: "For-Profit" },
  { name: "Providence Saint John's Health Center Santa Monica", city: "Santa Monica", state: "CA", beds: 234, idn_name: "Providence", idn_rank: 16, type: "General Acute Care", ownership: "Non-Profit" },
];
